import MainIntro from "./components/main-intro";

export default function Home() {
  return (
    <>
      <MainIntro />
      <div className="justify-center items-center">
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf

        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf

        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf

        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf

        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf

        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfas
        sdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsfsdfasdfasdfadsf

      </div>
    </>
  );
}
